credentials:
  usernames:
    angel:
      email: angel@gmail.com
      failed_login_attempts: 10
      logged_in: False
      name: Angel
      password: $2b$12$KCTxmlp0Mf4r6ngZkavOEOkb2.JhZsXczsnZZsfQbztHSmSrsib0W

cookie:
  expiry_days: 30
  key: 'angel-new'
  name: 'user_session'

pre-authorized:
  emails:
    - melsby@gmail.com
