[theme]
primaryColor="#055749"  # Brunswick Green 2 (used for accents)
backgroundColor="#F4F6F5"  # Ash Gray 2 (light background)
secondaryBackgroundColor="#9caba2ff"  # Ash Gray (secondary background)
textColor="#071a22ff"  # Rich Black (dark text for contrast)
font="sans serif"
